version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
  backend:
    build:
      context: ./go-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  socket:
    build:
      context: ./socket
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
